pipeline{
    agent any
    tools{
       nodejs 'node' 
    }
    parameters {
        booleanParam(name: 'RUN_NPM_INSTALL', defaultValue: true, description: 'Run npm install step')
    }
    environment{
        SONAR_HOME = tool('sonar-scanner')
        TAG = "${BUILD_NUMBER}"
    }

    stages{

        stage("cleanup"){
            steps{
                
                cleanWs()
            }
        }
        stage("checkout"){
            steps{
                git branch: "main", url: "https://github.com/edeogupc/jenkins.git"
            }
        }
        stage("static code anayysis"){
            steps{
                withSonarQubeEnv('SonarQube') {
                    sh '''
                
                       ${SONAR_HOME}/bin/sonar-scanner \
                        -Dsonar.projectName="zoba" \
                        -Dsonar.projectKey="zoba"
    
                    '''


 
                 }
            }
        }
        stage("wait for quality gate"){
            steps{
                
                script{
                    timeout(time: 10, unit: 'MINUTES') {
                       def ret = waitForQualityGate() 
                       if (ret.status != 'OK') {
                          error "The job failed because of quality gate status: ${ret.status}"
                        }
                    }
                }
            }
        }
        stages {
        stage("Install NPM Dependencies") {
            when {
                expression { params.RUN_NPM_INSTALL }
            }
            steps {
                sh "npm install"
            }
        }

        // other stages...
           }
           
        stage('OWASP FS SCAN') {
            steps {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit -n', odcInstallation: 'DP-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
              }
        }
        stage("trivy scan"){
            steps{
                sh ' trivy fs --exit-code 1 --severity CRITICAL,HIGH --format table ..'
            }
        }
        stage("docker build"){
            steps{
                sh ' docker build -t chumaedeogu/zobo:${TAG} .'
                
            }
        }

        stage("push to docker hub"){
            steps{
                echo "docker push will be here"
            }
        }





    }
    
    }
